### PR TITLE
ENH: Theme folder variables

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR adds functionality to configure theme paths and folders in the config file.An example  format of which is :- 

```
jupyter_theme = "qelectures" 
jupyter_theme_path = "theme" # default value is theme

jupyter_template_path = "theme/qelectures/templates" # default value is templates
jupyter_template_html = "lectures-nbconvert.tpl"
```

@mmcky do you want me to form `"theme/{}/templates".format(jupyter_theme)` in this manner?

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude -- we will need to pair this merge with PRs for 

- [ ] `lecture-source-py`
- [ ] `lecture-source-jl`
- [ ] `datascience`

`conf.py` updates and file reorganisation in the theme folder.

**Comment by AakashGfude** [comment]
Hi @mmcky have created PRs for the other branches, but I think I dont have access to the `datascience` branch

**Comment by mmcky** [comment]
thanks @AakashGfude I have given you write access now.

**Comment by mmcky** [comment]
@AakashGfude once you're happy with the testing on this -- please remove the `test` tag.

**Pull request merged**
