### PR TITLE
FEAT: Add nbconvert conversion from IPYNB to HTML

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds the ability to compile `html` from a collection of generated notebooks using `nbconvert`. This supports the use of templates to allow for customisation of pages during the conversion process. 

To allow this functionality add the following keys to `conf.py` configuration file.

`# generate html from IPYNB files

jupyter_generate_html = True
jupyter_html_template = "/path-to-template.tpl"`

This PR also has all the code of :-  https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/170 on top of which it is built.

### CODE REVIEW

**Comment by mmcky** [comment]
@AakashGfude thanks for all your work on this branch! 
I have just setup this PR for visibility of this new upcoming feature. Can you update the description with how to configure and use the `html` conversion. Thanks.

**Comment by AakashGfude** [comment]
> @AakashGfude thanks for all your work on this branch!
> I have just setup this PR for visibility of this new upcoming feature. Can you update the description with how to configure and use the `html` conversion. Thanks.

Done

**Comment by arnavs** [comment]
@AakashGfude if this is the thing you sent me, I think it's good to go on our end.

**Comment by mmcky** [comment]
thanks @AakashGfude this is looking great. Can you update CI or do you need me to look into that?

**Comment by mmcky** [comment]
thanks @AakashGfude. When you get the chance can you update `docs` to include this feature.

**Comment by AakashGfude** [comment]
> thanks @AakashGfude. When you get the chance can you update `docs` to include this feature.

@mmcky had written the conf variables needed at the end of the `Configuration` heading in  README.md . and had modified the summary to include the functionalities. Do tell me if I should add something more.

**Comment by mmcky** [comment]
hey @AakashGfude would you mind updating this PR to remove the conflicts?

**Comment by mmcky** [comment]
@AakashGfude let me know when you get this updated via slack and then I will merge and start updating the build server and getting preview updated.

**Comment by mmcky** [comment]
thanks @AakashGfude. This is a great addition.

**Pull request merged**
