### PR TITLE
FEAT: Add coverage reports for execution testing

### PR DESCRIPTION
**Pull request by AakashGfude**
`make coverage` command will create a coverage report

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude. I will review tonight.

**Comment by mmcky** [comment]
hey @AakashGfude now that we have a report we can use for the time being. Let's get this working when you're exams are over and then we can merge the PR.

**Comment by AakashGfude** [comment]
@mmcky this PR creates a folder `_build_coverage` for coverage reports. Updates individual task times at status.html for coverage reports and

**Comment by mmcky** [comment]
thanks @AakashGfude I will merge this now.

**Pull request merged**
