### PR TITLE
ENH: Update displaymath to use Latex tags rather than html table wrappers

### PR DESCRIPTION
**Pull request by mmcky**
This PR changes the implementation to use `\tag{}` for displaymath with id labels instead of html tables. This increases compatibility with `jupyterlab` and makes the notebook more readable. 

thanks @jlperla for the suggested solution. 

Currently it looks like `<a id="">` references don't work in jupyterlab. 

Image size issues are also resolved as all math is in the same environment.

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] use `quantecon.build.lectures` as a test case for this PR before merging

**Comment by mmcky** [comment]
this is broken in `linear_algebra` on the `python` side. So need to take a closer look tomorrow before merging this.

image

**Comment by mmcky** [comment]
It appears nbconvert is not honoring the `$$` environment for displaymath reliably. The html has injected html items within the math. The source for this bug is: 

```html
$$</p>
<h1 id="A-x">A x<a class="anchor-link" href="#A-x">&#182;</a></h1><p>\left[
\begin{array}{ccc}
    a_{11} &amp;  \cdots &amp; a_{1k} \\
    \vdots &amp; \vdots  &amp; \vdots \\
    a_{n1} &amp;  \cdots &amp; a_{nk}
\end{array}
\right]
\left[
\begin{array}{c}
    x_{1}  \\
    \vdots  \\
    x_{k}
\end{array}
\right]
:=
\left[
\begin{array}{c}
    a_{11} x_1 + \cdots + a_{1k} x_k \\
    \vdots \\
    a_{n1} x_1 + \cdots + a_{nk} x_k
\end{array}
\right] \tag{2}
$$</p>
```

**Comment by mmcky** [comment]
this is an issue with `nbconvert` and not our template.

**Comment by mmcky** [comment]
There is an issue already registered with nbconvert.
https://github.com/jupyter/nbconvert/issues/404

Will try and massage the LaTeX to get it to work.

**Comment by mmcky** [comment]
OK so the issue is the `=` on its own line. This is caught by `nbconvert` as markdown and breaks the equation environment. Given I am not sure how many edge cases there are here -- I am a bit reluctant to start editing our equations to fit around the `nbconvert` issue until the treatment of `$$` upstream is improved. @jlperla perhaps we should stick with wrapped equations in html for now -- what do you think?

**Comment by jlperla** [comment]
Is the `=` on its own line the only thing we know that triggers this?  If so, then that seems to be a regex we could easily check for in and fix across the lecture notes?

**Comment by mmcky** [comment]
From the issue on `nbonvert` -- open lists `[` also seem to break it. @jlperla do you had an RA that could check edge cases across the `jl` side I would be happy to coordinate updating on the `py` side. Its a bit tricky as they would need to diagnose on the IPYNB -> HTML border but they could do this on an individual lecture basis (without the template wrapper) using `jupyter nbconvert --to html file.ipynb``

**Comment by mmcky** [comment]
**Decision:** Modify `RST` files to suite buggy `nbconvert`

**Pull request merged**
