### PR TITLE
FEAT: contextual equation numbering for labelled display math

### PR DESCRIPTION
**Pull request by mmcky**
This PR re-adds equation numbering support for display formulae in a contextual way. If an equation has a label then it is wrapped in an ``html`` table with clear borders to enable proper placement of the equation number provided by sphinx.

- [x] test reference notebook needs to be added.

### CODE REVIEW

**Comment by jstac** [comment]
I see what you mean.  It's not ideal, to be honest.

Can we not have the equation number fully right aligned?  Perhaps then the equation will be more centered?

**Comment by mmcky** [comment]
What currently happens is an ``html`` table is drawn and the math is enclosed in a cell that is 75% of the width of the page and then centred within that column. I think the problem with ``right align`` is there is no common datum point as the look and feel of that will depend on the width of each equation. 

Another option (for now) would be to add a global ``conf.py`` property ``global_labelled_math = True`` that forces the use of ``html`` tables for positioning of math for common center point. This would remove the need to pre-parse but adds something to the configuration requirements, and all equations would be slightly left of centre.

**Comment by mmcky** [comment]
What I might try is reduce the table size for the numbers column to fit within a 10% width column, with a total text table width of 110% of the paragraph width. Maybe that would work.

**Comment by mmcky** [comment]
Ah for the time being what I will do is add a column on the left also to balance the table to match. 

```html
<a id='equation-eq_old1'></a>
<table width=100%>
<tr style='background-color: #FFFFFF !important;'>
<td width=5%></td>
<td width=90%>
$$
m_t - p_t = -\alpha(p_{t+1} - p_t) \: , \: \alpha > 0
$$
</td><td width=5% style='text-align:center !important;'>
(1)
</td></tr></table>
```

<a id='equation-eq_old1'></a>
<table width=100%>
<tr style='background-color: #FFFFFF !important;'>
<td width=5%></td>
<td width=90%>
$$
m_t - p_t = -\alpha(p_{t+1} - p_t) \: , \: \alpha > 0
$$
</td><td width=5% style='text-align:center !important;'>
(1)
</td></tr></table>

**Comment by mmcky** [comment]
Currently I have implemented this as ``3`` columns with ``width=10%`` for left and right to ensure equations remain balanced. This **may** present an issue for large numbers of equation numbers. 

This is what the test notebook renders like:

image

**Comment by mmcky** [comment]
In updating the test -- another style question arises. The ``labelled`` equations have a smaller font.

image

**Comment by jstac** [comment]
This looks great @mmcky, nice work.

**Comment by jstac** [comment]
@mmcky A differnt issue, but I feel like the text lines are too long and margins are too small.  It's well known that long lines put more strain on the eyes.  If you agree I'll open a separate issue.

**Comment by mmcky** [comment]
Thanks @jstac let's open a different issue re: line length.

**Pull request merged**
