### PR TITLE
improvements to project documentation

### PR DESCRIPTION
**Pull request by mmcky**
This PR adds various improvements to the projects documentation.

### CODE REVIEW

**Comment by jlperla** [comment]
For #21 it would be useful to have the minimal set of files required (instead of just the documentation) for people to test out (including the `conf.py` etc.)  Maybe just your basic regression test.

**Comment by mmcky** [comment]
Thanks @jlperla. I agree. A set of files (similar to those formed after `sphinx-quickstart` with the additional config) is a good idea. I will either add them to this repo under `example` or a separate repo `sphinxcontrib-jupyter.example`

**Comment by jlperla** [comment]
A separate repo is a great idea.  Then maybe after getting the initial files updated you can put into that any tricks you have for getting CI working?  Also, it was unclear to me how you are doing regression tests of the source-code, but I was pretty sure you were.  That would be an excellent addition down the road (is it like `doctest` strings, for example?)

**Comment by mmcky** [comment]
- [ ] setup a minimum example sphinx setup in ``sphinxcontrib-jupyter.minimal``

**Pull request merged**
