### PR TITLE
FEAT: Adding a pdf pipeline to allow conversion of rst files to pdf

### PR DESCRIPTION
**Pull request by AakashGfude**
This PR creates a new builder to read rst files and converts individual executed ipynb to pdf format using a `latex_tempate`, `nbconvert` and `pandoc`.

- [x] `pdf` files for individual pages

~~`book` pdf file for the whole website (jupyter_pdf_book = True)  **[Future Feature]**~~ has been  added as a tracked Issue #277 

- [x] The resulting `pdf` files should be located in `_build/jupyterpdf/pdf/` (@AakashGfude)

- [x] @AakashGfude provide summary of usage and options to help @mmcky with `docs`

**Testing:**

- [x] check `individual pdf` files against collection made by `ipynb_pdf_constructor` (`python`) @mmcky 
- [x] add test cases to `tests/pdf` @AakashGfude

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] adjust travis to include `xelatex` (Issue #214)

**Comment by mmcky** [comment]
- [ ] @AakashGfude can we add compatibility with `python27` by updating `subprocess.run()` to `subprocess.call()` if using `python2`?

**Comment by mmcky** [comment]
fixes #214

**Comment by mmcky** [comment]
@AakashGfude has found a resource to assist with adding a template approach to the `pdf` compilation chain. https://michaelgoerz.net/notes/custom-template-for-converting-jupyter-notebooks-to-latex.html.

This is a good way to go.

**Comment by mmcky** [comment]
@AakashGfude this doesn't need to be implemented for this PR but it is related (see Issue #229)

**Comment by mmcky** [comment]
@AnjuJoon @AakashGfude  with the new additions to the Wiki page. Should we implement those in `translate_all` for the `jupyter_target_pdf` compilation option.

**Comment by mmcky** [comment]
- [ ] Once happy with the solution being produce -- we need to update the reference `ipynb` for travis to pass for PR #211

**Comment by mmcky** [comment]
- [ ] add details of `jupyterpdf` builder to `docs`

**Comment by mmcky** [comment]
- [ ] add file filter option `jupyter_pdf_excludepatterns` for `index*` and `404` rst files etc.

**Comment by mmcky** [comment]
@AakashGfude is it ok to execute `pdf` in parallel? Does each process maintain a different `bib` file for the references?

**Comment by mmcky** [comment]
@AakashGfude are these warnings `normal` status codes from `xelatex` (i.e. should we be checking for a `status code = 2`)

**Comment by mmcky** [comment]
```

**Comment by mmcky** [comment]
- [ ] setup PR in `lecture-source-jl` for `making-pdf` branch.

**Comment by mmcky** [comment]
- [ ] copy `_static` to all subfolders during `pdf` compilation. (Removal is tracked in https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/279 for `0.6.0`)

**Comment by mmcky** [comment]
@AakashGfude I have opened a tracking issue for resolving the `xelatex` warnings

https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/280

**Comment by mmcky** [comment]
thanks @AakashGfude the latest commit is working nicely. Just one item - the `_static` folder isn't required in the `pdf` folder if you wanted to not copy it across. Cheers. Matt

**Comment by mmcky** [comment]
@AakashGfude working on test case for `pdf`. This `warning` is being flagged when not needed. 

```bash
WARNING: Theme folder not present. Consider creating a theme folder for static assets
```

**Comment by mmcky** [comment]
@AakashGfude I think a lot of the current `xelatex` warnings are when there are no references to add to the `References` section which are appended to each file? We could check if any references are added and if they are then add the references to the `latex` file (or specify as an option for manual control)

image

**Comment by mmcky** [comment]
- [ ] check reference solution for `pdf` test case with @AakashGfude

**Comment by mmcky** [comment]
Does the extension check if `xelatex` is installed before executing? Perhaps we should add a check and issue a warning that `pdf` compilation is not possible without `xelatex`. I am happy to fix on using `xelatex` as that supports unicode.

**Comment by AakashGfude** [comment]
> * [x]  Does the extension check if `xelatex` is installed before executing? Perhaps we should add a check and issue a warning that `pdf` compilation is not possible without `xelatex`. I am happy to fix on using `xelatex` as that supports unicode. @AakashGfude I have added this in commit [194c78e](https://github.com/QuantEcon/sphinxcontrib-jupyter/commit/194c78e637547411701e48c3477db3fe6898d81d) at the builder stage. Is this the best place for this?

Looks good to me @mmcky .

**Comment by AakashGfude** [comment]
> ~thanks @AakashGfude the latest commit is working nicely. Just one item - the `_static` folder isn't required in the `pdf` folder if you wanted to not copy it across. Cheers. Matt~ Actually I know why there is static there - as it is picking up the `pdf` files in the _static. Let's leave this for now and open a tracking issue to fix later.

right. we can have an exclude patterns or we can store the subdirectories of lectures while we are building them, and only copy pdf's from those folders

**Comment by mmcky** [comment]
- [ ] @AakashGfude default behaviour when copying support files should be to overwrite. This bug crops up when running a second run using `sphinx` cache after modification of a single `RST` file.

```bash
Exception occurred:
  File "/home/qebuild/anaconda3/envs/latest/lib/python3.7/shutil.py", line 561, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/home/qebuild/repos/lecture-source-jl/_build/jupyterpdf/pdf/more_julia/_static/pdfs/pi2.pdf' already exists
```

**Comment by mmcky** [comment]
Looking into some bugs. Do you know whey

```rst
.. figure:: /_static/figures/judd_fig2.png
    :width: 70

Inventories trend to a common steady state

If we increase the depreciation rate to :math:`\delta = 0.05`, then we expect steady state inventories to fall

This is indeed the case, as the next figure shows


.. figure:: /_static/figures/judd_fig1.png
    :width: 70
```

is converted to

```tex
\end{tcolorbox}
        
    \includegraphics{_static/figures/judd_fig2.png}\\
Inventories trend to a common steady state

If we increase the depreciation rate to \(\delta = 0.05\), then we
expect steady state inventories to fall

This is indeed the case, as the next figure shows

\begin{figure}
\centering
\includegraphics{_static/figures/judd_fig1.png}
\caption{\_static/figures/judd\_fig1.png}
\end{figure}
```

one figure is correctly converted to `figure` while the other is only an `includegraphics`

**Comment by mmcky** [comment]
- [ ] fix bug from `datascience` test set. We should make `_static` an optional copy.

```
Exception occurred:
  File "/home/qebuild/anaconda3/envs/latest/lib/python3.7/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/qebuild/repos/lecture-source-ds/_build/jupyterpdf/executed/_static'
The full traceback has been saved in /tmp/sphinx-err-qhby3ouu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:58: recipe for target 'pdf' failed
make: *** [pdf] Error 2
```

**Comment by mmcky** [comment]
hey @AakashGfude can you please check https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/211/commits/c87a4596cfc8b19c40d6ebb2b93d9b4279927a62 as I modified the condition to check for `source` folder and then copy to ensure latest version.

**Comment by mmcky** [comment]
- [ ] @AakashGfude why do we specify `-D jupyter_latex_templ
ate="theme/templates/latex.tpl"` in the `Makefile`. Shouldn't this be `latex.tpl`?

**Comment by AakashGfude** [comment]
> * [ ]  @AakashGfude why do we specify `-D jupyter_latex_template="theme/templates/latex.tpl"` in the `Makefile`. Shouldn't this be `latex.tpl` given we have `template_path`?

good catch. The branch started before that implementation, and went unnoticed. will modify it accordingly.

**Comment by arnavs** [comment]
I tried clicking an equation link in the `McCall` PDF and it pointed me to the website. Shouldn't it point me to the equation in the same PDF?

**Comment by AakashGfude** [comment]
- [ ]  `getting_started` and `julia_environment` are in same folder `getting_started_julia` and the link in `getting_started` looks like this - [interacting with julia](julia_environment.ipynb), but it should have the subdirectory as well, for the website link to work

**Comment by mmcky** [comment]
@AakashGfude we still have some non general code in this PR we will need to address in `writers/process_latex.py`
```
    ## maketitle tex issue  need to change this 
    if(filename =="coase"):
         data = data.replace("Coase?s", "Coase's")

    if(filename == "dyn_stack"):
        data = data.replace("vs.~Stackelberg", "vs. Stackelberg")
        data = data.replace("vs.stackelberg", "vs-stackelberg")
    return data
```

**Comment by mmcky** [comment]
@AakashGfude running the final test run now.

**Comment by mmcky** [comment]
- [ ] @mmcky initiate a final test run

**Pull request merged**
